CREATE TABLE  "ADHERENT" 
   (	"ID_ADHERENT" NUMBER, 
	"NOM" VARCHAR2(4000), 
	"PRENOM" VARCHAR2(4000), 
	"CIN" VARCHAR2(4000), 
	"CNE" VARCHAR2(4000), 
	 CONSTRAINT "ADHERENT_PK" PRIMARY KEY ("ID_ADHERENT") ENABLE
   )
/
CREATE TABLE  "DEPARTEMENT" 
   (	"ID_DEPARTEMENT" NUMBER, 
	"DESIGNATION" VARCHAR2(4000), 
	 CONSTRAINT "DEPARTEMENT_PK" PRIMARY KEY ("ID_DEPARTEMENT") ENABLE
   )
/
CREATE TABLE  "MATERIEL" 
   (	"ID_MATERIEL" NUMBER, 
	"DESIGNATION" VARCHAR2(4000), 
	"PRIXHT" NUMBER, 
	"TVA" NUMBER, 
	"CATEGORIE" VARCHAR2(4000), 
	"IMAGE" VARCHAR2(4000), 
	"ETAT" VARCHAR2(4000), 
	 CONSTRAINT "MATERIEL_PK" PRIMARY KEY ("ID_MATERIEL") ENABLE
   )
/
CREATE TABLE  "AFFECTER" 
   (	"ID_MATERIEL" NUMBER, 
	"ID_DEPARTEMENT" NUMBER, 
	"DATE_AFFECTATION" DATE, 
	 CONSTRAINT "AFFECTER_PK" PRIMARY KEY ("ID_DEPARTEMENT") ENABLE, 
	 CONSTRAINT "AFFECTER_FK2" FOREIGN KEY ("ID_MATERIEL")
	  REFERENCES  "MATERIEL" ("ID_MATERIEL") ENABLE, 
	 CONSTRAINT "AFFECTER_FK3" FOREIGN KEY ("ID_DEPARTEMENT")
	  REFERENCES  "DEPARTEMENT" ("ID_DEPARTEMENT") ENABLE
   )
/
CREATE TABLE  "AUTEUR" 
   (	"ID_AUTEUR" NUMBER, 
	"NOM" VARCHAR2(4000), 
	"PRENOM" VARCHAR2(4000), 
	"DATE_NAISSANCE" VARCHAR2(4000), 
	"NATIONALITE" VARCHAR2(4000), 
	 CONSTRAINT "AUTEUR_PK" PRIMARY KEY ("ID_AUTEUR") ENABLE
   )
/
CREATE TABLE  "RESPONSABLE" 
   (	"ID_RESPONSABLE" NUMBER, 
	"NOM" VARCHAR2(4000), 
	"PRENOM" VARCHAR2(4000), 
	"GRADE" VARCHAR2(4000), 
	"CIN" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	 CONSTRAINT "RESPONSABLE_PK" PRIMARY KEY ("ID_RESPONSABLE") ENABLE
   )
/
CREATE TABLE  "DEMANDE" 
   (	"ID_EMETTEUR" NUMBER, 
	"FROM_ADMIN" NUMBER(1,0), 
	"DATE_ENVOIE" DATE, 
	"ID_RESPONSABLE" NUMBER, 
	 CONSTRAINT "DEMANDE_PK" PRIMARY KEY ("ID_EMETTEUR") ENABLE, 
	 CONSTRAINT "DEMANDE_FK" FOREIGN KEY ("ID_RESPONSABLE")
	  REFERENCES  "RESPONSABLE" ("ID_RESPONSABLE") ENABLE
   )
/
CREATE TABLE  "LIVRE" 
   (	"ISBN" VARCHAR2(4000), 
	"TITRE" VARCHAR2(4000), 
	"LANGUE" VARCHAR2(4000), 
	"NBR_PAGE" NUMBER, 
	"DATE_PARUTION" DATE, 
	"IMAGE_LIVRE" VARCHAR2(4000), 
	 CONSTRAINT "LIVRE_PK" PRIMARY KEY ("ISBN") ENABLE
   )
/
CREATE TABLE  "EXEMPLAIRE" 
   (	"ID_EXEMPLAIRE" NUMBER, 
	"ETAT" VARCHAR2(4000), 
	"ISBN" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "EXEMPLAIRE_PK" PRIMARY KEY ("ID_EXEMPLAIRE") ENABLE, 
	 CONSTRAINT "EXEMPLAIRE_CON" FOREIGN KEY ("ISBN")
	  REFERENCES  "LIVRE" ("ISBN") ENABLE
   )
/
CREATE TABLE  "EMPRUNTER" 
   (	"ID_ADHERENT" NUMBER, 
	"ID_EXEMPLAIRE" NUMBER, 
	"DATE_EMPRUNT" DATE, 
	"DATE_RETOUR" DATE, 
	"RENDU" NUMBER, 
	 CONSTRAINT "EMPRUNTER_PK" PRIMARY KEY ("ID_ADHERENT", "ID_EXEMPLAIRE") ENABLE, 
	 CONSTRAINT "EMPRUNTER_CON" FOREIGN KEY ("ID_ADHERENT")
	  REFERENCES  "ADHERENT" ("ID_ADHERENT") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "EMPRUNTER_CON1" FOREIGN KEY ("ID_EXEMPLAIRE")
	  REFERENCES  "EXEMPLAIRE" ("ID_EXEMPLAIRE") ENABLE
   )
/
CREATE TABLE  "GERER" 
   (	"ID-DEPARTEMENT" NUMBER, 
	"ID_RESPONSABLE" NUMBER, 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	 CONSTRAINT "GERER_PK" PRIMARY KEY ("ID-DEPARTEMENT", "ID_RESPONSABLE") ENABLE, 
	 CONSTRAINT "GERER_FK" FOREIGN KEY ("ID-DEPARTEMENT")
	  REFERENCES  "DEPARTEMENT" ("ID_DEPARTEMENT") ENABLE, 
	 CONSTRAINT "GERER_FK2" FOREIGN KEY ("ID_RESPONSABLE")
	  REFERENCES  "RESPONSABLE" ("ID_RESPONSABLE") ENABLE
   )
/
CREATE TABLE  "PUBLIER" 
   (	"ISBN" VARCHAR2(4000), 
	"ID_AUTEUR" NUMBER, 
	 CONSTRAINT "PUBLIER_PK" PRIMARY KEY ("ISBN", "ID_AUTEUR") ENABLE, 
	 CONSTRAINT "PUBLIER_CON" FOREIGN KEY ("ISBN")
	  REFERENCES  "LIVRE" ("ISBN") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PUBLIER_CON1" FOREIGN KEY ("ID_AUTEUR")
	  REFERENCES  "AUTEUR" ("ID_AUTEUR") ENABLE
   )
/
CREATE UNIQUE INDEX  "ADHERENT_PK" ON  "ADHERENT" ("ID_ADHERENT")
/
CREATE UNIQUE INDEX  "AFFECTER_PK" ON  "AFFECTER" ("ID_DEPARTEMENT")
/
CREATE UNIQUE INDEX  "AUTEUR_PK" ON  "AUTEUR" ("ID_AUTEUR")
/
CREATE UNIQUE INDEX  "DEMANDE_PK" ON  "DEMANDE" ("ID_EMETTEUR")
/
CREATE UNIQUE INDEX  "DEPARTEMENT_PK" ON  "DEPARTEMENT" ("ID_DEPARTEMENT")
/
CREATE UNIQUE INDEX  "EMPRUNTER_PK" ON  "EMPRUNTER" ("ID_ADHERENT", "ID_EXEMPLAIRE")
/
CREATE UNIQUE INDEX  "EXEMPLAIRE_PK" ON  "EXEMPLAIRE" ("ID_EXEMPLAIRE")
/
CREATE UNIQUE INDEX  "GERER_PK" ON  "GERER" ("ID-DEPARTEMENT", "ID_RESPONSABLE")
/
CREATE UNIQUE INDEX  "LIVRE_PK" ON  "LIVRE" ("ISBN")
/
CREATE UNIQUE INDEX  "MATERIEL_PK" ON  "MATERIEL" ("ID_MATERIEL")
/
CREATE UNIQUE INDEX  "PUBLIER_PK" ON  "PUBLIER" ("ISBN", "ID_AUTEUR")
/
CREATE UNIQUE INDEX  "RESPONSABLE_PK" ON  "RESPONSABLE" ("ID_RESPONSABLE")
/
 CREATE SEQUENCE   "ADHERENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "AUTEUR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DEMANDE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "DEPARTEMENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "EXEMPLAIRE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "LIVRE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MATERIEL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "RESPONSABLE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "USERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_ADHERENT" 
  before insert on "ADHERENT"               
  for each row  
begin   
    select "ADHERENT_SEQ".nextval into :NEW.ID_ADHERENT from dual; 
end; 

/
ALTER TRIGGER  "BI_ADHERENT" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_AUTEUR" 
  before insert on "AUTEUR"               
  for each row  
begin   
    select "AUTEUR_SEQ".nextval into :NEW.ID_AUTEUR from dual; 
end; 

/
ALTER TRIGGER  "BI_AUTEUR" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DEMANDE" 
  before insert on "DEMANDE"               
  for each row  
begin   
    select "DEMANDE_SEQ".nextval into :NEW.ID_EMETTEUR from dual; 
end; 

/
ALTER TRIGGER  "BI_DEMANDE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_DEPARTEMENT" 
  before insert on "DEPARTEMENT"               
  for each row  
begin   
    select "DEPARTEMENT_SEQ".nextval into :NEW.ID_DEPARTEMENT from dual; 
end; 

/
ALTER TRIGGER  "BI_DEPARTEMENT" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_EXEMPLAIRE" 
  before insert on "EXEMPLAIRE"               
  for each row  
begin   
    select "EXEMPLAIRE_SEQ".nextval into :NEW.ID_EXEMPLAIRE from dual; 
end; 

/
ALTER TRIGGER  "BI_EXEMPLAIRE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_LIVRE" 
  before insert on "LIVRE"               
  for each row  
begin   
    select "LIVRE_SEQ".nextval into :NEW.ISBN from dual; 
end; 

/
ALTER TRIGGER  "BI_LIVRE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MATERIEL" 
  before insert on "MATERIEL"               
  for each row  
begin   
    select "MATERIEL_SEQ".nextval into :NEW.ID_MATERIEL from dual; 
end; 

/
ALTER TRIGGER  "BI_MATERIEL" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_RESPONSABLE" 
  before insert on "RESPONSABLE"               
  for each row  
begin   
    select "RESPONSABLE_SEQ".nextval into :NEW.ID_RESPONSABLE from dual; 
end; 

/
ALTER TRIGGER  "BI_RESPONSABLE" ENABLE
/